### PR TITLE
CMake Tweaks

### PR DESCRIPTION
**Pull request by JJL772**
* Tweaked install layout of Smaug. Previously it was non-functional after install, it still is here... will require a bit of work to get it to respect the standard unix install layout (bin/ lib/ share/), but shouldn't be too bad. BGFX also installs to a GNU style layout by default, so running install causes some weird stuff (like bgfx installing it's docs to share/doc lol) 
* Added install and copy rules for assets. Should make development a bit easier, especially for newbs

### CODE REVIEW

**Comment by ozxybox** [comment]
Rad! It's been needing a good way to install required files easily for so long; I've by manually copying hah. You said there's more work to do, do you want me to hold off from merging in both of these PRs for now? Otherwise, the PR seems good.

**Comment by JJL772** [comment]
`make install` was already broken before this PR since smaug didn't even get installed (but bgfx did, including it's docs). Smaug will require some filesystem tweaks to work right with the GNU-style install structure (e.g. it will need to look for `assets/` and then `../share/smaug/assets` if it can't load anything). If you don't want to have install rules like that, we can just remove them since they're not useful anyway.

**Comment by JJL772** [comment]
It can work with no changes if you just install the assets and shaders to `bin/` next to the smaug executable, but in that case I would suggest wrapping the install directives in `if(NOT UNIX)` lol

**Comment by ozxybox** [comment]
I'll merge this onto a branch and get the fs to support it. Thank you!!

**Pull request merged**
