### PR TITLE
Various fixes made for CI, mostly to log{.h,.cpp}

### PR DESCRIPTION
**Pull request by Nopey**
This should fix the CI failure, which was caused by usage of the nonstandard `alloca` extension.
The code could also use a temporary heap allocation at a fairly reasonable performance cost, or a longer-lived global allocation protected by a lock ([the call to printf is already using locking](https://stackoverflow.com/questions/23586682/how-to-use-printf-in-multiple-threads#40186101))

### CODE REVIEW

**Comment by ozxybox** [comment]
Did a bit of reading, and it seems like VLAs are a GCC extension to C++; MSVC despises it. Might be best to use an #ifdef for GCC and use a VLA and alloca on MSVC? Not sure what the standard way of make variable allocations to the stack is. What do you think?

**Comment by Nopey** [comment]
oh, I suppose VLAs are only standard in C.
I think I'll quickly write the global allocation w. lock version I mentioned above

**Comment by ozxybox** [comment]
Awesome! 👍

**Comment by minexew** [comment]
Why not a `thread_local` malloc'd buffer?

Then you wouldn't have to use non-standard extensions + risk smashing your stack.

**Comment by Nopey** [comment]
oh, thread_local is an option
thought it was introduced in c++17, but thread_local would work.
Is there a benefit to using less locking? Only if someone `SetSink`'s with a nonlocking sink..
thread_local would give each thread its own buffer, and I'm unsure of the performance implications of TLS.

**Comment by ozxybox** [comment]
Looks good! Good potential reuse for other future formatting related code. The global saddens me a little, but what do you do when it's a template like that; plus it's name spaced off, so it shouldn't be a problem. The only thing that comes to mind as a potential improvement is wrapping `_g_priv_fmt_buf` with a "temp memory" function that could call reserve and return ``.data()`` to prevent potential fiddling with the vector. Love the thread_local, never knew about it before. Very cool!

**Comment by ozxybox** [comment]
I'll test this and pull it in when I get home.

**Comment by Nopey** [comment]
CI just failed: https://github.com/Nopey/Smaug/runs/2747740616
but not because of the logging, rather, someone was using C++20 consteval and MSVC-specific DebugBreak

**Comment by Nopey** [comment]
okay, well, those were used in the logging. but it wasn't the logging TLS buffer :)

**Comment by ozxybox** [comment]
Hah, that would be me. I should probably increase the cpp version to 20 in the cmake list. Thought I already had, but I must've made a mistake somewhere... Forgot you could use compilers other than MSVC on windows HAH, I'll have to fix that as well.

**Comment by Nopey** [comment]
I'm currently replacing the DebugBreak with https://github.com/scottt/debugbreak

**Comment by ozxybox** [comment]
Awesome single header lib! I appreciate the fixes!!

**Comment by Nopey** [comment]
The build will continue to fail until either:
* We remove consteval
* The [image](https://github.com/actions/virtual-environments/blob/ubuntu20/20210531.0/images/linux/Ubuntu2004-README.md) updates to [gcc 10, where consteval is supported](https://gcc.gnu.org/projects/cxx-status.html#cxx20)

**Comment by ozxybox** [comment]
Looks like we might be able to use `__GNUC__` to check the compiler version to ensure the code always compiles, but running that function often would be subpar... Could we update the GCC version manually via the build action? Would slow the action *even further*, but would allow the code to stay in use with the old image.

**Comment by ozxybox** [comment]
Actually, should just be fine with a compiler check, the function only runs once.

**Comment by Nopey** [comment]
I've removed the consteval and constexpr markers when the compiler is G++ pre-10, CI is running: https://github.com/Nopey/Smaug/runs/2749459769

**Comment by ozxybox** [comment]
Awesome stuff! Thank you!

**Pull request merged**
